version: 2.1

jobs:
  build:
    docker:
      - name: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm_packages"
          paths:
            - "npm_packages/src/node_modules"
      - run: npm run lint
  test:
   docker:
      - name: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: "npm_packages"
      - run: npm i
      - run: npm run test
  analyze:
   docker:
      - name: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: "npm_packages"
      - run: npm i
      - run: npm audit
workflow:
  react_pipeline:
    jobs:
     - build
     - test:
      requires:
        build
    - analyze:
      requires:
        test

